name: devops test

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: get code from github
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          sudo rm -rf /be02-ansible-practice 
          sudo git clone https://github.com/SongYeonBaek/be02-ansible-practice.git
          sudo rm -rf /var/www/html/main.html
          sudo mv -f /be02-ansible-practice/*.html /var/www/html
          sudo systemctl reload nginx

          
